import { NextResponse } from "next/server";
import {
  ABILITIES,
  ALL_ITEM_KEYS,
  COMBAT,
  DEFAULT_LOOT_FILTER,
  EQUIP_SLOTS,
  ITEMS,
  ITEM_LIST,
  MONSTERS,
  RIVALS,
  xpForLevel,
} from "@/lib/game/content";
import { MAP_H, MAP_W, REGIONS, TEMPLE, TILE, TILE_DEFS } from "@/lib/game/world";

export const dynamic = "force-static";

/**
 * Live balance endpoint for the Godot client.
 * Same payload as shared/content.json (generated by npm run export:content).
 * Godot WebSync can fetch this instead of the baked data/content.json
 * to always get the latest web numbers during development.
 */
export async function GET() {
  return NextResponse.json({
    version: 1,
    exportedAt: new Date().toISOString(),
    balance: {
      COMBAT,
      xpForLevelSamples: Object.fromEntries(
        [1, 2, 3, 5, 8, 10, 12].map((l) => [l, xpForLevel(l)])
      ),
    },
    items: ITEMS,
    itemList: ITEM_LIST.map((i) => i.key),
    monsters: MONSTERS,
    abilities: ABILITIES,
    equipSlots: EQUIP_SLOTS,
    defaultLootFilter: DEFAULT_LOOT_FILTER,
    allItemKeys: ALL_ITEM_KEYS,
    rivals: RIVALS,
    world: { MAP_W, MAP_H, TILE, TEMPLE, REGIONS, TILE_DEFS },
  });
}
